config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :user_id, :post_id, presence: true
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :logged_in_user, only: %i[create destroy]
	before_action :correct_user,   only: :destroy


	def create
		@post = Post.find(params[:post_id])
		@user = current_user
		@comment = @post.comments.build(comment_params)
    	@comment.user_id = current_user.id
    	if @comment.save
      		flash[:success] = "Comment created"
      	end
      	redirect_to post_path(@post)
	end		

	def destroy
		@comment.destroy
  	flash[:success] = "Comment deleted"
 		redirect_to request.referrer || root_url
	end


	private
    def comment_params
    	params.require(:comment).permit(:content)
    end

    def correct_user
      @comment = current_user.comments.find_by(id: params[:id])
      redirect_to root_url if @comment.nil?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
 <li id="comment-<%= comment.id %>" class="list-group-item">
 	<div class="row">
 		<div class="col-md-2">
 			<%= link_to gravatar_for(comment.user, size: 50), comment.user %>
 		</div>
 		<div class="col-md-10">
	 		<div class="meta">
	 			<span class="user"><%= link_to comment.user.name, comment.user %></span>
	 			<span class="timestamp"><%= time_ago_in_words(comment.created_at) %> ago</span>
	 		</div>
	 		<div class="content"><%= comment.content %></div>
	 		<div class="controls">
	 			<% if current_user?(comment.user) %>
		 			<%= link_to "<span class='glyphicon glyphicon-remove' aria-hidden=''></span> Delete".html_safe, post_comment_path(@post, comment), method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-default' %>
		 		<% end %>
	 		</div>
 		</div>
 	</div>
 </li>