config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_comment_form.html.erb
<%= form_for [@post, @comment], html: { class: 'form-inline special-form' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group smaller">
    <%= f.text_field :content, placeholder: "Type your text here...", class: 'form-control' %>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <b>The form contains <%= pluralize(object.errors.count, "error") %>:</b>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ul class="posts list-group">
    <%= render @feed_items %>
  </ul>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_pointed_user.html.erb
<div class="well">
	<div class="text-center">
		<%= link_to gravatar_for(@user, size: 50), @user %>
		<h3><%= link_to @user.name, @user %></h3>
		<ul class="list-group text-left">
			<li class="list-group-item">
				<span class="text-left">Posts</span>
				<span class='badge'><%= @user.posts.count %></span>
			</li>
			<%= render 'shared/stats' %>
		</ul>
	</div>
</div>

app/views/shared/_post_form.html.erb
<%= form_for @post, html: { class: 'form-inline special-form' } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.text_field :content, placeholder: "Type your text here...", class: 'form-control input-lg' %>
  </div>
  <%= f.submit "Post", class: "btn btn-danger btn-lg" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<li class="list-group-item">
  <a href="<%= following_user_path(@user) %>">
    Following
  </a>
  <span class="badge">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
  </span>
</li>
<li class="list-group-item">
  <a href="<%= followers_user_path(@user) %>">
    Followers
  </a>
  <span class="badge">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </span>
</li>

app/views/shared/_user_info.html.erb
<div class="well">
	<div class="text-center">
		<%= link_to gravatar_for(current_user, size: 50), current_user %>
		<h3><%= link_to current_user.name, current_user %></h3>
		<ul class="list-group text-left">
			<li class="list-group-item">
				<span class="text-left">Posts</span>
				<span class='badge'><%= current_user.posts.count %></span>
			</li>
			<%= render 'shared/stats' %>
		</ul>
	</div>
</div>