config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts do
    resources :comments,          only: [:create, :destroy]
  end
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="text-center">
		<hr>
		Course Work <br>
		Made by Yaroslav Krempokha<br>
		2016
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand back" href="/"><%= image_tag "imind.png",  alt: "icon", class: "icon" %>iMind</a>
      </div>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right back">
          <% if logged_in? %>
            <li class="<%= active_class(root_path) %>"><%= link_to "Posts feed", root_path, class: "nav-buttons" %></li>
            <li class="<%= active_class(posts_path) %>"><%= link_to "<span class='glyphicon glyphicon-search'></span> Search posts".html_safe, posts_path, class: "nav-buttons" %></li>
            <li class="<%= active_class(users_path) %>"><%= link_to "Users", users_path, class: "nav-buttons" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li class="<%= active_class(login_path) %>"><%= link_to "Sign in", login_path %></li>
            <li class="<%= active_class(signup_path) %>"><%= link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag 'imind.png' %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>